# Generated by Django 5.2.17 on 2026-09-18 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def make_share_token():
    """Kept here so this historical migration stays importable on its own."""
    return ""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('quantity_needed', models.PositiveIntegerField(default=1)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('product_url', models.URLField(blank=True, help_text="Where to buy it, if there's a good link.")),
                ('image_url', models.URLField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Waiting to be contacted'), ('contacted', 'Contacted'), ('fulfilled', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='registry.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('share_token', models.CharField(default=make_share_token, max_length=32, unique=True)),
                ('intro', models.TextField(blank=True, help_text='Shown at the top of the public page. Who this is for, why.')),
                ('contact_note', models.CharField(blank=True, help_text="Shown after someone claims an item, e.g. 'John will email you this week.'", max_length=240)),
                ('notify_email', models.EmailField(blank=True, help_text="Claim notifications are emailed here. Defaults to the owner's email.", max_length=254)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'registries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='registry.registry'),
        ),
    ]
