# Generated by Django 5.2.17 on 2026-09-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_claim_split_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at'], 'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['position', 'created_at'], 'verbose_name': 'item', 'verbose_name_plural': 'itens'},
        ),
        migrations.AlterModelOptions(
            name='registry',
            options={'ordering': ['pk'], 'verbose_name': 'enxoval', 'verbose_name_plural': 'enxovais'},
        ),
        migrations.RemoveField(
            model_name='registry',
            name='share_token',
        ),
        migrations.RemoveField(
            model_name='registry',
            name='slug',
        ),
        migrations.AlterField(
            model_name='claim',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='message',
            field=models.TextField(blank=True, verbose_name='recado'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantidade'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('pending', 'Aguardando contato'), ('contacted', 'Contato feito'), ('fulfilled', 'Recebido'), ('cancelled', 'Cancelado')], default='pending', max_length=12, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='preço estimado'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='link da foto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=160, verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='posição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_url',
            field=models.URLField(blank=True, help_text='Onde comprar, se houver um bom link.', verbose_name='link do produto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_needed',
            field=models.PositiveIntegerField(default=1, verbose_name='quantidade necessária'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='contact_note',
            field=models.CharField(blank=True, help_text="Aparece depois que alguém reserva um item, ex.: 'Entraremos em contato esta semana.'", max_length=240, verbose_name='mensagem de agradecimento'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='intro',
            field=models.TextField(blank=True, help_text='Aparece no topo da página pública. Para quem é o enxoval e por quê.', verbose_name='introdução'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='publicado'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='notify_email',
            field=models.EmailField(blank=True, help_text='Para onde vão os avisos de reserva. Sem isso, usa o e-mail da conta.', max_length=254, verbose_name='e-mail para avisos'),
        ),
        migrations.AlterField(
            model_name='registry',
            name='title',
            field=models.CharField(max_length=140, verbose_name='título'),
        ),
    ]
